<a href="https://colab.research.google.com/github/OMKARTT/DeepLearningImages/blob/main/Copy_of_Task_03.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### Task 03:

In this task, you have to implement the Backpropagation method using Pytorch. This is particularly useful when the hypothesis function contains several weights.

**Backpropagation**: Algorithm to caculate gradient for all the weights in the network with several weights. 

* It uses the `Chain Rule` to calcuate the gradient for multiple nodes at the same time. 
* In pytorch this is implemented using a `variable` data type and `loss.backward()` method to get the gradients

In [ ]:
# import the necessary libraries
import torch
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

## Preliminaries - Pytorch Basics

In [ ]:
# creating a tensor

# zero tensor
zeros = torch.zeros(5)
print(zeros)
# ones
ones = torch.ones(5)
print(ones)
# random normal
random = torch.randn(5)
print(random)


# creating tensors from list and/or numpy arrays
my_list = [0.0, 1.0, 2.0, 3.0, 4.0]
to_tensor = torch.Tensor(my_list)
print("The size of the to_tensor: ", to_tensor.size())

my_array = np.array(my_list) # or
to_tensor = torch.tensor(my_array)
to_tensor = torch.from_numpy(my_array)
print("The size of the to_tensor: ", to_tensor.size())

tensor([0., 0., 0., 0., 0.])
tensor([1., 1., 1., 1., 1.])
tensor([-2.0946, -0.9915,  0.1418, -0.5610, -0.7242])
The size of the to_tensor:  torch.Size([5])
The size of the to_tensor:  torch.Size([5])


In [ ]:
type(to_tensor)

torch.Tensor

In [ ]:
# multi dimenstional tensors

# 2D
two_dim = torch.randn((3, 3))
print(two_dim)
# 3D 
three_dim = torch.randn((3, 3, 3))
print(three_dim)

tensor([[ 0.6537, -0.7042,  0.9797],
        [ 1.8178, -2.0760, -0.7152],
        [-1.2221,  0.4611,  0.3189]])
tensor([[[-0.1435,  0.3757, -2.2724],
         [-1.0421,  0.0659, -0.9382],
         [ 0.1961,  0.4217,  0.3726]],

        [[-2.1512, -0.2162,  1.1968],
         [-0.6359,  0.3017,  0.6338],
         [ 0.9777, -2.4478,  0.6590]],

        [[-0.5593, -0.2238,  0.6782],
         [ 0.9307, -2.1583, -0.9311],
         [-1.2095,  0.3169, -0.0143]]])


In [ ]:
# tensor shapes and axes

print(zeros.shape)
print(two_dim.shape)
print(three_dim.shape)

# zeroth axis - rows
print(two_dim[:, 0])
# first axis - columns
print(two_dim[0, :])

torch.Size([5])
torch.Size([3, 3])
torch.Size([3, 3, 3])
tensor([ 0.6537,  1.8178, -1.2221])
tensor([ 0.6537, -0.7042,  0.9797])


In [ ]:
print(two_dim[:, 0:2])
print(two_dim[0:2, :])

tensor([[ 0.6537, -0.7042],
        [ 1.8178, -2.0760],
        [-1.2221,  0.4611]])
tensor([[ 0.6537, -0.7042,  0.9797],
        [ 1.8178, -2.0760, -0.7152]])


In [ ]:
rand_tensor = torch.randn(2,3)
print("Tensor Shape : " , rand_tensor.shape)
resized_tensor = rand_tensor.reshape(3,2)
print("Resized Tensor Shape : " , resized_tensor.shape) # or
resized_tensor = rand_tensor.reshape(3,-1)
print("Resized Tensor Shape : " , resized_tensor.shape)
flattened_tensor = rand_tensor.reshape(-1)
print("Flattened Tensor Shape : " , flattened_tensor.shape)

Tensor Shape :  torch.Size([2, 3])
Resized Tensor Shape :  torch.Size([3, 2])
Resized Tensor Shape :  torch.Size([3, 2])
Flattened Tensor Shape :  torch.Size([6])


Determine the derivative of $y = 2x^{3} + x$ at $x = 1$

In [ ]:
x = torch.tensor(2.0, requires_grad = True)
y = 2 * (x ** 3) + x
y.backward()
print("Value of Y at x=1 : " , y)
print("Derivative of Y wrt x at x=1 : " , x.grad)

Value of Y at x=1 :  tensor(18., grad_fn=<AddBackward0>)
Derivative of Y wrt x at x=1 :  tensor(25.)


### Task 03 - a
Determine the partial derivative of $y = uv + u^{2}$ at $u=1$ and $v=2$ with respect to $u$ and $v$.

In [ ]:
# YOUR CODE STARTS HERE
u = torch.tensor(1.0,requires_grad=True)
v = torch.tensor(2.0,requires_grad=True)
y =u*v+u**2
y.backward()
# YOUR CODE ends HERE
print("Value of y at u=1, v=2 : " , y)
print("Partial Derivative of y wrt u : " , u.grad)
print("Partial Derivative of y wrt v : " , v.grad)

Value of y at u=1, v=2 :  tensor(3., grad_fn=<AddBackward0>)
Partial Derivative of y wrt u :  tensor(4.)
Partial Derivative of y wrt v :  tensor(1.)


#### Hypothesis Function and Loss Function

$y = x * w + b$

$loss =(\hat{y}-y)^2$

Let us make use of a randomly-created sample dataset as follows

In [ ]:
#sample-dataset
x_data = [1.0, 2.0, 3.0]
y_data = [2.0, 4.0, 6.0]

## Task: 03 - b
Declare pytorch tensors for weight and bias and implement the forward and loss function of our model

In [ ]:
# Define w = 1 and b = -1 for y = wx + b
# Note that w,b are learnable paramteter 
# i.e., you are going to take the derivative of the tensor(s).
# YOUR CODE STARTS HERE
w = 
b = 
# YOUR CODE ENDS HERE

assert w.item() == 1
assert b.item() == -1
assert w.requires_grad == True
assert b.requires_grad == True

In [ ]:
#forward function to calculate y_pred for a given x according to the linear model defined above
def forward(x):
    #implement the forward model to compute y_pred as w*x + b
    ## YOUR CODE STARTS HERE


    ## YOUR CODE ENDS HERE

#loss-function to compute the mean-squared error between y_pred and y_actual
def loss(y_pred, y_actual):
    #calculate the mean-squared-error between y_pred and y_actual
    ## YOUR CODE STARTS HERE


    ## YOUR CODE ENDS HERE

Calculate $y_{pred}$ for $x=4$ without training the model

In [ ]:
y_pred_without_train = forward(4)

Begin Training

In [ ]:
# In this method, we learn the dataset multiple times (called epochs)
# Each time, the weight (w) gets updates using the graident decent algorithm based on weights of the previous epoch

alpha = 0.01 # Let us set learning rate as 0.01
weight_list = []
loss_list=[]

# Training loop
for epoch in range(10):
    total_loss = 0
    count = 0
    
    for x, y in zip(x_data, y_data):
        
        #implement forward pass, compute loss and gradients for the weights and update weights
        ## YOUR CODE STARTS HERE
        
        ## YOUR CODE ENDS HERE

        # Manually zero the gradients after updating weights
        w.grad.data.zero_()
        
        count += 1
        
    avg_mse = total_loss / count        
    print(f"Epoch: {epoch+1} | Loss: {avg_mse.item()} | w: {w.item()}")
    weight_list.append(w)
    loss_list.append(avg_mse)  

Calculate $y_{pred}$ for $x=4$ after training the model

In [ ]:
y_pred_with_train = forward(4)

print("Actual Y Value for x=4 : 8")
print("Predicted Y Value before training : " , y_pred_without_train.item())
print("Predicted Y Value after training : " , y_pred_with_train.item())

## Task: 03 - c
Repeat **Task:03 - b** for the quadratic model defined below

#### Using backward propagation for quadratic model

$\hat{y} = x^2*w_{2} + x*w_{1}$

$loss = (\hat{y}-y)^2$

* Using Dummy values of x and y

`x = 1,2,3,4,5`
`y = 1,6,15,28,45`

In [ ]:
x_data = [1.0, 2.0, 3.0, 4.0, 5.0]
y_data = [1.0, 6.0, 15.0, 28, 45]

In [ ]:
# Visualize the given dataset
plt.plot(x_data,y_data)
plt.show()

In [ ]:
# Initialize w2 and w1 with randon values
w_1 = torch.tensor([1.0], requires_grad=True)
w_2 = torch.tensor([1.0], requires_grad=True)

In [ ]:
#wuadratic-forward function to calculate y_pred for a given x according to the quadratic model defined above
def quad_forward(x):
    #implement the forward model to compute y_pred as w1*x + w2*(x^2)
    ## YOUR CODE STARTS HERE


    ## YOUR CODE ENDS HERE

#loss-function to compute the mean-squared error between y_pred and y_actual
def loss(y_pred, y_actual):
    #calculate the mean-squared-error between y_pred and y_actual
    ## YOUR CODE STARTS HERE


    ## YOUR CODE ENDS HERE

Calculate $y_{pred}$ for $x=6$ without training the model

In [ ]:
y_pred_without_train = quad_forward(6)

Begin Training

In [ ]:
# In this method, we learn the dataset multiple times (called epochs)
# Each time, the weight (w) gets updates using the graident decent algorithm based on weights of the previous epoch

alpha = 0.0012 # Let us set learning rate as 0.01
weight_list = []
loss_list=[]

# Training loop
for epoch in range(100):
    total_loss = 0
    count = 0
    
    for x, y in zip(x_data, y_data):
        
        #implement forward pass, compute loss and gradients for the weights and update weights
        ## YOUR CODE STARTS HERE
        
        ## YOUR CODE ENDS HERE
        
        # Manually zero the gradients after updating weights
        w_1.grad.data.zero_()
        w_2.grad.data.zero_()
        
        count += 1
        
    avg_mse = total_loss / count        
    print(f"Epoch: {epoch+1} | Loss: {avg_mse.item()} | w: {w.item()}")
    weight_list.append(w)
    loss_list.append(avg_mse)

Calculate $y_{pred}$ for $x=6$ after training the model

In [ ]:
y_pred_with_train = forward(6)

print("Actual Y Value for x=4 : 66")
print("Predicted Y Value before training : " , y_pred_without_train.item())
print("Predicted Y Value after training : " , y_pred_with_train.item())